export {panic} from 'panicit'
export {defineWrapConfig, type TWrapConfig as WrapConfig} from './config'
export {err, ok, setPanic, wrap} from './result'
export type {Result, WrapOption} from './result'
export {toWrap} from './toWrap'
export type {TF, TP, TR} from './types'
