export {panic} from 'panicit'
export {defineWrapConfig} from './config'
export type {Panic, TWrapConfig as WrapConfig} from './config'
export {err, ok, setPanic, wrap} from './result'
export type {Result, WrapOption} from './result'
export {toWrap} from './toWrap'
